"use client";

import { AnalysisResult } from "@/lib/types";

interface Props {
  data: AnalysisResult;
}

export default function ExportReport({ data }: Props) {
  const { user, analysis, languages, activity, totalStars, totalForks, activeRepos } = data;

  const generateReport = () => {
    const skillBars = analysis.skillScores
      .map((s) => {
        const filled = Math.round(s.score / 5);
        const empty = 20 - filled;
        return `  ${s.category.padEnd(12)} ${"█".repeat(filled)}${"░".repeat(empty)} ${s.score}/100`;
      })
      .join("\n");

    const langList = languages
      .slice(0, 8)
      .map((l) => `  ${l.name.padEnd(16)} ${l.percentage}% (${l.count} repos)`)
      .join("\n");

    const topRepos = analysis.topRepos
      .slice(0, 5)
      .map((r) => `  ${r.name.padEnd(28)} Score: ${r.qualityScore}/100  ★${r.stars}  ${r.language || "N/A"}`)
      .join("\n");

    const report = `
╔══════════════════════════════════════════════════════════════╗
║                    DEVLENS AI REPORT                        ║
║              Developer Portfolio Intelligence                ║
╚══════════════════════════════════════════════════════════════╝

Generated: ${new Date(data.analyzedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
Platform:  https://devlens-ai.vercel.app

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DEVELOPER PROFILE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Name:           ${user.name || user.login}
  GitHub:         github.com/${user.login}
  Location:       ${user.location || "Not specified"}
  Company:        ${user.company || "Not specified"}
  Career Level:   ${analysis.careerLevel}
  Specialization: ${analysis.specialization}
  Followers:      ${user.followers}
  Public Repos:   ${user.public_repos}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

KEY METRICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Total Stars:    ${totalStars}
  Total Forks:    ${totalForks}
  Active Repos:   ${activeRepos} (last 6 months)
  Activity:       ${activity.totalEvents} events (last 90 days)
  Current Streak: ${activity.streak} days
  Peak Coding:    ${activity.busiestDay}s at ${activity.peakHour > 12 ? activity.peakHour - 12 + " PM" : activity.peakHour + " AM"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

AI ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${analysis.summary}

STRENGTHS:
${analysis.strengths.map((s) => `  ✦ ${s}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SKILL SCORES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${skillBars}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

LANGUAGE DISTRIBUTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${langList}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TOP REPOSITORIES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${topRepos}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${analysis.recommendations.map((r, i) => `  ${i + 1}. ${r}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report generated by DevLens AI — devlens-ai.vercel.app
`.trim();

    const blob = new Blob([report], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `devlens-report-${user.login}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyShareLink = () => {
    const url = `${window.location.origin}/analyze/${user.login}`;
    navigator.clipboard.writeText(url);
  };

  return (
    <div className="flex flex-wrap gap-2">
      <button
        onClick={generateReport}
        className="group flex items-center gap-2 px-4 py-2 bg-accent-cyan/10 text-accent-cyan text-xs font-semibold rounded-xl border border-accent-cyan/20 hover:bg-accent-cyan/20 hover:border-accent-cyan/40 transition-all"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Download Report
      </button>
      <button
        onClick={copyShareLink}
        className="group flex items-center gap-2 px-4 py-2 bg-surface-2 text-txt-secondary text-xs font-semibold rounded-xl border border-surface-4 hover:border-accent-violet/30 hover:text-accent-violet transition-all"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
        </svg>
        Copy Share Link
      </button>
    </div>
  );
}
